name = "FactoryWorks"
author = "kc00l"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "894f5b8fa35eea0077418c53028eec6e6d8929ae488add64c5c810763bdf1266"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"
