name = "Planetary Factory"
author = "kc00l"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07b36e9cc3198b6dc1a65a62a2054d8cd57f704efc5f025d409ec4b94da6bb9c"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"
