#!/usr/bin/env python3
"""Assert the Pack's models are current against their .bbmodel sources, and that the generator
refuses a source that breaks ADR-0112.

  - `scripts/build-model-assets.py --check` holds every generated model and texture current.
  - The committed template, exported as if it were a machine, gives a base model and three status
    children, each child naming its kit lamp.
  - Each rule is broken once on a copy of the template, and the generator must name it.

Usage: tests/pack/test_model_assets.py
"""

import copy
import importlib.util
import json
import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "scripts/build-model-assets.py"


def png(width, height):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))

    rows = b"".join(b"\x00" + b"\xff\xff\xff\xff" * width for _ in range(height))
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(rows))
        + chunk(b"IEND", b"")
    )


def light(model):
    return model["elements"][0]


def link_texture(name, size):
    def setup(machine):
        (machine / name).write_bytes(png(size, size))

    def edit(model):
        model["textures"][0]["relative_path"] = name

    return setup, edit


def foreign_model(assets):
    path = assets / "models/block/lamp.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('{"parent": "minecraft:block/cube_all"}')


def orphan_model(assets):
    path = assets / "models/block/gone.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('{"credit": "Generated by scripts/build-model-assets.py from somewhere"}')


bad_name = link_texture("Bad Name.png", 4)

# (refusal the generator must name, edit to the template, setup in the machine folder, setup in
# the assets, the source's file name)
BREAKS = [
    ("is embedded", lambda m: m["textures"][0].update(source="data:image/png;base64,AA==")),
    ("absolute path", lambda m: m["textures"][0].update(path="/Users/someone/lamp.png")),
    ("outside data/art/models/", lambda m: m["textures"][0].update(
        relative_path="../../../../kubejs/assets/factoryworks/textures/block/steel_chest.png")),
    ("Blockbench format 4.10", lambda m: m["meta"].update(format_version="4.10")),
    ("model format bedrock", lambda m: m["meta"].update(model_format="bedrock")),
    ("Java block version latest", lambda m: m.update(java_block_version="latest")),
    ("reference images", lambda m: m.update(reference_images=[{"name": "factorio.png"}])),
    ("off the 1/16 grid", lambda m: light(m).update(to=[10.5, 4, 1])),
    ("beyond a vanilla model's reach", lambda m: light(m).update(**{"from": [6, 0, -17]})),
    ("inflated", lambda m: light(m).update(inflate=0.5)),
    ("22.5 degree steps", lambda m: light(m).update(rotation=[0, 30, 0])),
    ("22.5 degree steps", lambda m: light(m).update(rotation=[22.5, 22.5, 0])),
    ("22.5 degree steps", lambda m: light(m).update(rotation=[0, 67.5, 0])),
    ("not a valid resource name", bad_name[1], bad_name[0]),
    ("named after its folder", lambda m: None, None, None, "other.bbmodel"),
    ("was not written by this generator", lambda m: None, None, foreign_model),
    ("orphan", lambda m: None, None, orphan_model),
]


def load_generator(sources, assets):
    spec = importlib.util.spec_from_file_location("build_model_assets", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.SOURCES = sources
    module.KIT = sources / "kit"
    module.TEMPLATE = sources / "template"
    module.ASSETS = assets
    return module


def export(template, edit=None, machine_setup=None, assets_setup=None, file_name="lamp.bbmodel"):
    """The generator's errors and files for the template, edited, exported as machine `lamp`."""
    work = pathlib.Path(tempfile.mkdtemp()).resolve()
    try:
        sources, assets = work / "models", work / "assets"
        shutil.copytree(ROOT / "data/art/models", sources)
        machine = sources / "lamp"
        machine.mkdir()
        model = copy.deepcopy(template)
        if edit:
            edit(model)
        if machine_setup:
            machine_setup(machine)
        if assets_setup:
            assets_setup(assets)
        (machine / file_name).write_text(json.dumps(model))
        errors = []
        files = load_generator(sources, assets).planned_files(errors)
        return errors, {path.relative_to(assets).as_posix(): data for path, data in files.items()}
    finally:
        shutil.rmtree(work)


def main():
    failures = []
    generated = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"], capture_output=True, text=True
    )
    if generated.returncode != 0:
        failures.append(f"{GENERATOR.relative_to(ROOT)} --check: {generated.stderr.strip()}")

    template = json.loads((ROOT / "data/art/models/template/template.bbmodel").read_text())
    errors, files = export(template)
    if errors:
        failures.append(f"the template as a machine is refused: {errors}")
    for status, lamp in {"working": "status_light_working", "blocked": "status_light_blocked",
                         "no_power": "status_light_no_power"}.items():
        child = files.get(f"models/block/lamp_{status}.json")
        if child is None:
            failures.append(f"no {status} child")
        elif json.loads(child)["textures"]["status"] != f"factoryworks:block/kit/{lamp}":
            failures.append(f"the {status} child names {json.loads(child)['textures']}")
    base = json.loads(files.get("models/block/lamp.json", b"{}"))
    element = (base.get("elements") or [{}])[0]
    if element.get("light_emission") != 15 or element.get("shade") is not False:
        failures.append(f"the status light lost its glow: {element}")
    if element.get("faces", {}).get("north", {}).get("uv") != [0, 0, 16, 16]:
        failures.append(f"the lamp face's UV is not rescaled to 0-16: {element.get('faces')}")

    for expected, edit, *setups in BREAKS:
        machine_setup, assets_setup, file_name = (setups + [None, None, None])[:3]
        errors, _ = export(template, edit, machine_setup, assets_setup, file_name or "lamp.bbmodel")
        if not any(expected in error for error in errors):
            failures.append(f"a source with {expected!r} is not refused: {errors}")

    if failures:
        print("FAIL")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print(f"OK -- generator current; template exports; {len(BREAKS)} broken sources refused")
    return 0


if __name__ == "__main__":
    sys.exit(main())
