#!/usr/bin/env python3
"""Assert Terra's five ore blocks still agree with everything that names them (ADR-0041).

The blocks are registered in Java, their amounts are extracted from Factorio, their sprites and
their assets are generated by two scripts, and GregTech's Miner finds them by a tag. That is five
places one ore has to be named in, and the failures are all quiet:

  - **A block with no amounts behind it.** `OreResource.java` and the extracted slice the mod loads
    must deal the same five keys. A block outside the slice throws at class-init; a resource in the
    slice that nothing registers is ore Terra can never place.
  - **A drop that drifts.** `OreResource.java` and `scripts/build-ore-assets.py` each state which
    item an ore pays out -- the mod for a player's draw, and nothing at all for an explosion. If they
    disagree, a patch pays one item by hand and a different one to TNT, which no check but this
    one would ever see.
  - **A stage with no variant.** One blockstate variant per stage the slice deals, per ore. That
    each variant's model and texture resolve is `test_block_assets.py`'s (#254).
  - **The tag GregTech actually scans.** `MinerLogic` reads NeoForge's `Tags.Blocks.ORES`, so
    `c:ores` is what decides whether rung 1's drill can see a pack-authored ore block at all. ADR-0041
    names this as the risk that gates the whole body, and it is one line of JSON to get wrong.
  - **A drop that names nothing.** `OreMining.drop` turns an id no mod registers into air rather
    than a throw, so the draw is spent and the hand stays empty. Each drop is resolved against the
    installed jars the way `test_item_map.py` resolves an item-map target (#321).
  - **Borrowed art with no credit.** A sprite `scripts/build-ore-textures.py` derives from someone
    else's texture holds only with attribution, so the source and every stage are named in `NOTICE`.
  - **A generated file edited by hand.** Both scripts' `--check` runs here, so a sprite or a
    blockstate edited in place is a failure rather than a thing that survives until the next
    regeneration silently reverts it.

Usage: tests/pack/test_ore_assets.py
"""
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import test_item_map  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent.parent

SLICE = ROOT / "mod/src/main/resources/factoryworks_core/ore/amounts.json"
RESOURCE_JAVA = ROOT / "mod/src/main/java/com/factoryworks/core/ore/OreResource.java"
ASSETS = ROOT / "kubejs/assets/factoryworks"
DATA = ROOT / "kubejs/data"

# The tag GregTech's Miner scans. Not decoration: `MinerLogic` reads `Tags.Blocks.ORES`, which is
# this file, and a block missing from it is invisible to every drill on the ladder.
ORES_TAG = DATA / "c/tags/block/ores.json"

def java_resources(source):
    """The enum's five entries: corpus key and drop item."""
    return {
        key: drop
        for key, drop in re.findall(r'\w+\("([a-z_]+)",\s*"([a-z0-9_:]+)"\)', source)
    }


def script_drops():
    """The drops `scripts/build-ore-assets.py` writes into the loot tables."""
    source = (ROOT / "scripts/build-ore-assets.py").read_text()
    body = source[source.index("ORES = {"):source.index("# The tags every one")]
    return {
        key: drop
        for key, drop in re.findall(r'"([a-z]+)":\s*\{"drop":\s*"([a-z0-9_:]+)"', body)
    }


def unresolved_drop(drop):
    """Why a drop names nothing, or None when it resolves or cannot be asked on this machine."""
    namespace = drop.partition(":")[0]
    if namespace == "minecraft" and not test_item_map.vanilla_lang():
        return None
    if test_item_map.resolves(drop):
        return None
    return "no installed jar registers it"


def main():
    failures = []
    slice_ = json.loads(SLICE.read_text())
    corpus = slice_["resources"]
    java = java_resources(RESOURCE_JAVA.read_text())
    drops = script_drops()

    if set(java) != set(corpus):
        failures.append(
            f"OreResource registers {sorted(java)} and the extracted slice deals {sorted(corpus)}"
        )
    if java != drops:
        for key in sorted(set(java) | set(drops)):
            if java.get(key) != drops.get(key):
                failures.append(
                    f"{key} drops {java.get(key)} by hand and {drops.get(key)} to an explosion"
                )

    for key, drop in sorted(java.items()):
        reason = unresolved_drop(drop)
        if reason:
            failures.append(f"{key} pays out {drop}, and {reason}: every draw would pay air")

    stages = max((len(entry["stage_ratios"]) for entry in corpus.values()), default=0)
    if stages < 2:
        failures.append(f"the slice carries {stages} stages; there is nothing to render")

    for ore in sorted(java):
        block = f"{ore}_ore"
        blockstate = ASSETS / "blockstates" / f"{block}.json"
        if not blockstate.is_file():
            failures.append(f"{block} has no blockstate")
            continue
        variants = json.loads(blockstate.read_text())["variants"]
        if len(variants) != stages:
            failures.append(
                f"{block} has {len(variants)} blockstate variants against {stages} stages"
            )
        for stage in range(stages):
            if f"stage={stage}" not in variants:
                failures.append(f"{block} has no variant for stage={stage}")

        loot = DATA / "factoryworks/loot_table/blocks" / f"{block}.json"
        if loot.is_file() and json.loads(loot.read_text()).get("pools"):
            # ADR-0041 rejects "a hand break taking one unit and destroying the remainder" because
            # it "hands the player a way to vandalise a patch for one ore". A loot table that pays
            # out is that route wearing TNT: a thousand-unit block gone for one free item. The
            # metered path is OreMining.drop, and it is the only one.
            failures.append(
                f"{block}'s loot table pays out -- an explosion would buy a whole block's amount "
                "for one item, which is the vandalism route ADR-0041 closed")

    if "tooltip.factoryworks.ore.jade.amount" not in json.loads(
            (ASSETS / "lang/en_us.json").read_text()):
        failures.append("the Jade line has no lang key, so the amount would render as a raw key")

    if not ORES_TAG.is_file():
        failures.append("no c:ores tag -- GregTech's Miner scans it, and would see no pack ore")
    else:
        tagged = set(json.loads(ORES_TAG.read_text())["values"])
        missing = {f"factoryworks:{ore}_ore" for ore in java} - tagged
        if missing:
            failures.append(f"{sorted(missing)} are outside c:ores, so no drill can see them")

    notice = (ROOT / "NOTICE").read_text()
    textures = (ROOT / "scripts/build-ore-textures.py").read_text()
    sourced = re.search(r"^SOURCED = (\{.*\})$", textures, re.M)
    if not sourced:
        failures.append("scripts/build-ore-textures.py has no one-line SOURCED table to read credits from")
    for ore, art in (json.loads(sourced.group(1)) if sourced else {}).items():
        credited = [f"data/art/{art}"] + [
            f"kubejs/assets/factoryworks/textures/block/ore/{ore}_stage{n}.png" for n in range(stages)]
        for file in credited:
            if file not in notice:
                failures.append(f"{file} is borrowed art with no credit in NOTICE")

    for script in ("build-ore-textures.py", "build-ore-assets.py"):
        run = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / script), "--check"],
            capture_output=True, text=True)
        if run.returncode != 0:
            failures.append(f"scripts/{script} --check: {run.stdout.strip() or run.stderr.strip()}")

    for index, failure in enumerate(failures, 1):
        print(f"FAIL {index}: {failure}")
    if failures:
        return 1
    print(f"ok   {len(java)} ore blocks x {stages} stages, drops agree and resolve, all in c:ores")
    return 0


if __name__ == "__main__":
    sys.exit(main())
