#Whether to use FTB Teams' API for team logic instead of Researchd's own.
#This disables the team screen and team command
use_ftb_teams = false

[energy]
	#Energy consumed per tick by a Research Lab while it is researching. Zero disables the feature.
	# Default: 0
	# Range: 0 ~ 1073741823
	research_lab_energy_usage = 30
	#Size of a Research Lab's energy buffer and its per-tick transfer limit. Min: 2 x Usage
	# Default: 100000
	# Range: > 1
	research_lab_energy_capacity = 100000
