package com.planetaryfactory.core.reach;

import com.planetaryfactory.core.PlanetaryFactoryCore;
import com.planetaryfactory.core.energy.EnergyOwner;

import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.event.entity.EntityAttributeModificationEvent;
import net.neoforged.neoforge.event.entity.player.PlayerInteractEvent;

/** The player's Reach (#413). */
public final class Reach {

    public static final double BLOCKS = 16.0;

    private static final double SERVER_LENIENCE = 1.0;

    /** Generated by {@code scripts/build-building-tag.py}. */
    public static final TagKey<Block> BUILDINGS = TagKey.create(Registries.BLOCK,
            Identifier.fromNamespaceAndPath(PlanetaryFactoryCore.NAMESPACE, "buildings"));

    private Reach() {
    }

    /**
     * The base value rather than a modifier added on login, so a respawned or freshly constructed
     * player has it with nothing to re-apply, and creative's own bonus still stacks on top.
     */
    public static void onEntityAttributes(EntityAttributeModificationEvent event) {
        event.add(EntityType.PLAYER, Attributes.BLOCK_INTERACTION_RANGE, BLOCKS);
    }

    /**
     * Only the start is asked: a break begun in reach finishes as vanilla's does, since the client's
     * hold is never asked again.
     */
    public static void onLeftClickBlock(PlayerInteractEvent.LeftClickBlock event) {
        if (event.getAction() == PlayerInteractEvent.LeftClickBlock.Action.START
                && refusesBreak(event.getEntity(), event.getPos())) {
            event.setCanceled(true);
        }
    }

    /**
     * The server allows vanilla's own 1.0 for the position it lags the client by, because a start the
     * client allowed and the server refused leaves a ghost break.
     */
    public static boolean refusesBreak(Player player, BlockPos pos) {
        Level level = player.level();
        double reach = Attributes.BLOCK_INTERACTION_RANGE.value().getDefaultValue()
                + (level.isClientSide() ? 0.0 : SERVER_LENIENCE);
        return !isBuilding(level, pos) && new AABB(pos).distanceToSqr(player.getEyePosition()) >= reach * reach;
    }

    /** A footprint's part blocks and a rig's are the machine their anchor is. */
    private static boolean isBuilding(Level level, BlockPos pos) {
        BlockPos owner = EnergyOwner.of(level, pos);
        return level.getBlockState(owner == null ? pos : owner).is(BUILDINGS);
    }
}
