#!/usr/bin/env python3
"""Emit the Personal Assembler's hand copies from the pack's assembling recipes (#291, ADR-0089).

Craftworks plans only with `craftworks:assembling`, and a recipe id has one type, so every recipe in
ADR-0063's hand set gets a second file: `recipe/assembling/<path>.json` becomes
`recipe/hand/<path>.json`. The hand set is every `factoryworks:assembling` recipe whose
`category` is `crafting`, whichever script wrote it (the corpus converter, the Engineer's Pick
recipes, the stock re-authoring). A hand recipe with a fluid or with other than one result fails the
run: the Personal Assembler plans only through items and one result.

It also writes `kubejs/server_scripts/hand_recipes.js`, the `<path>`s that have a copy. Craftworks
asks Researchd about the copy's own id, so `factorio_tech_dsl.js` adds the copy of every machine
recipe a research unlocks.

Usage:

    scripts/build-hand-recipes.py            # writes the copies and the id list
    scripts/build-hand-recipes.py --check    # asserts both are current; no writes
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RECIPES = ROOT / "kubejs/data/factoryworks/recipe"
MACHINE = RECIPES / "assembling"
HAND = RECIPES / "hand"
ID_LIST = ROOT / "kubejs/server_scripts/hand_recipes.js"

HAND_CATEGORY = "crafting"


def copies():
    out, failures = {}, []
    for path in sorted(MACHINE.rglob("*.json")):
        recipe = json.loads(path.read_text(encoding="utf-8"))
        if recipe.get("category") != HAND_CATEGORY:
            continue
        stem = path.relative_to(MACHINE).with_suffix("").as_posix()
        if recipe.get("fluid_ingredients") or recipe.get("fluid_results"):
            failures.append(f"{stem}: a fluid, which the Personal Assembler cannot hold")
            continue
        if len(recipe["results"]) != 1:
            failures.append(f"{stem}: {len(recipe['results'])} results, and the Personal Assembler plans one")
            continue
        out[stem] = {
            "type": "craftworks:assembling",
            "ingredients": recipe["ingredients"],
            "results": recipe["results"],
            "time": recipe["time"],
        }
    if failures:
        sys.exit("\n".join(f"FAIL {line}" for line in failures))
    return out


def id_list(stems):
    lines = ["// priority: 10",
             "// Generated by scripts/build-hand-recipes.py; do not edit. `var` so factorio_tech_dsl.js sees it.",
             "var PF_HAND_RECIPES = ["]
    lines += [f"  '{stem}'," for stem in stems]
    lines += ["]", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    emitted = {stem: json.dumps(body, indent=2) + "\n" for stem, body in copies().items()}
    ids = id_list(sorted(emitted))
    written = {p.relative_to(HAND).with_suffix("").as_posix(): p.read_text(encoding="utf-8")
               for p in sorted(HAND.rglob("*.json"))} if HAND.is_dir() else {}

    if args.check:
        stale = sorted(set(emitted) ^ set(written)) + sorted(
            s for s in set(emitted) & set(written) if emitted[s] != written[s])
        if not ID_LIST.is_file() or ID_LIST.read_text(encoding="utf-8") != ids:
            stale.append(ID_LIST.name)
        if stale:
            sys.exit("stale: " + ", ".join(stale) + " -- run scripts/build-hand-recipes.py")
        print(f"OK -- {len(emitted)} hand recipes")
        return

    for stem in set(written) - set(emitted):
        (HAND / f"{stem}.json").unlink()
    for path in sorted(HAND.rglob("*"), reverse=True) if HAND.is_dir() else []:
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    for stem, text in emitted.items():
        path = HAND / f"{stem}.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    ID_LIST.write_text(ids, encoding="utf-8")
    print(f"wrote {len(emitted)} hand recipes under {HAND.relative_to(ROOT)} and {ID_LIST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
