#!/usr/bin/env python3
"""Write the Pack's block models from their Blockbench sources (ADR-0112).

Every `data/art/models/<machine>/<machine>.bbmodel` becomes
`kubejs/assets/factoryworks/models/block/<machine>.json`, plus one child per status that sets its
`#status` texture to that status's lamp from `data/art/models/kit/` (ADR-0111). Each PNG a model
links is copied to `kubejs/assets/factoryworks/textures/block/<path under data/art/models>`.
`template/` is held to the rules but not exported.

The element and face fields are Blockbench 5.2.1's Java block codec, ported: cubes in outliner
order, face UVs stored in project pixels and written in vanilla's 0-16. Fields the game does not
read are left out, except `credit`, which marks a model as this generator's so a hand-made model is
never overwritten and an orphaned one is found.

Usage:

    scripts/build-model-assets.py            # writes the models and textures
    scripts/build-model-assets.py --check    # asserts they are current and every source obeys
                                             # ADR-0112; no writes
"""
import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCES = ROOT / "data/art/models"
KIT = SOURCES / "kit"
TEMPLATE = SOURCES / "template"
ASSETS = ROOT / "kubejs/assets/factoryworks"
NAMESPACE = "factoryworks"
CREDIT = "Generated by scripts/build-model-assets.py"

FORMAT_VERSION = "5.0"
MODEL_FORMAT = "java_block"
JAVA_BLOCK_VERSION = "1.21.11"
RESOURCE_NAME = re.compile(r"^[a-z0-9_./-]+$")
STATUS_VARIABLE = "status"
STATUS_LAMPS = {
    "working": "status_light_working",
    "blocked": "status_light_blocked",
    "no_power": "status_light_no_power",
}
FACE_AXES = {  # the two cube axes a face spans, horizontal first
    "north": (0, 1), "south": (0, 1),
    "east": (2, 1), "west": (2, 1),
    "up": (0, 2), "down": (0, 2),
}


def rel(path):
    path = pathlib.Path(path).resolve()
    return path.relative_to(ROOT.resolve()).as_posix() if path.is_relative_to(ROOT.resolve()) else str(path)


def source_path(png):
    return png.resolve().relative_to(SOURCES.resolve())


def texture_link(png):
    return f"{NAMESPACE}:block/{source_path(png).with_suffix('').as_posix()}"


def texture_destination(png):
    return ASSETS / "textures/block" / source_path(png)


def turned_axes(cube):
    return [i for i, angle in enumerate(cube.get("rotation", [0, 0, 0])) if angle]


def number(value):
    """A whole float as an int, so 16.0 is written 16."""
    return int(value) if value == int(value) else value


def outliner_order(model):
    """Cubes in Blockbench's export order: the outliner tree, depth first."""
    by_uuid = {cube.get("uuid"): cube for cube in model.get("elements", [])}
    ordered = []

    def walk(nodes):
        for node in nodes:
            if isinstance(node, str):
                if node in by_uuid:
                    ordered.append(by_uuid[node])
            elif isinstance(node, dict):
                walk(node.get("children", []))

    walk(model.get("outliner", []))
    return ordered if model.get("outliner") else list(by_uuid.values())


class Source:
    """One .bbmodel being compiled, and the rule breaks found in it."""

    def __init__(self, path, errors):
        self.path = path
        self.errors = errors
        self.errors_before = len(errors)
        self.model = json.loads(path.read_text(encoding="utf-8"))
        resolution = self.model.get("resolution", {})
        self.project_size = (resolution.get("width", 16), resolution.get("height", 16))
        self.textures = self.model.get("textures", [])
        self.pngs = [self.resolve(texture) for texture in self.textures]

    def refuse(self, message):
        self.errors.append(f"{rel(self.path)}: {message}")

    def check_header(self):
        meta = self.model.get("meta", {})
        if meta.get("format_version") != FORMAT_VERSION:
            self.refuse(f"Blockbench format {meta.get('format_version')}, not {FORMAT_VERSION}")
        if meta.get("model_format") != MODEL_FORMAT:
            self.refuse(f"model format {meta.get('model_format')}, not {MODEL_FORMAT}")
        if self.model.get("java_block_version") != JAVA_BLOCK_VERSION:
            self.refuse(
                f"Java block version {self.model.get('java_block_version')}, "
                f"not {JAVA_BLOCK_VERSION}"
            )
        if self.model.get("reference_images"):
            self.refuse("saves reference images, which would ship (ADR-0103)")

    def resolve(self, texture):
        name = texture.get("name", "?")
        if texture.get("source"):
            self.refuse(f"texture {name} is embedded; link it instead")
        if texture.get("path"):
            self.refuse(f"texture {name} saves an absolute path")
        relative = texture.get("relative_path")
        if not relative:
            self.refuse(f"texture {name} has no relative path")
            return None
        png = (self.path.parent / relative).resolve()
        if SOURCES.resolve() not in png.parents:
            self.refuse(f"texture {name} lies outside data/art/models/")
            return None
        if not png.is_file():
            self.refuse(f"texture {name} links {relative}, which does not exist")
            return None
        if not RESOURCE_NAME.match(source_path(png).as_posix()):
            self.refuse(f"texture {name} is not a valid resource name: {source_path(png)}")
            return None
        return png

    def check_cube(self, cube, where):
        corners = cube["from"] + cube["to"]
        if any(c != int(c) for c in corners):
            self.refuse(f"{where} is off the 1/16 grid ({cube['from']} -> {cube['to']})")
        if any(c < -16 or c > 32 for c in corners):
            self.refuse(f"{where} is beyond a vanilla model's reach of -16..32")
        if cube.get("inflate"):
            self.refuse(f"{where} is inflated, which leaves the 1/16 grid")
        angles = [cube["rotation"][i] for i in turned_axes(cube)]
        if len(angles) > 1 or any(a % 22.5 or abs(a) > 45 for a in angles):
            self.refuse(f"{where} is rotated {cube['rotation']}; one axis in 22.5 degree steps")

    def compile_face(self, face):
        out = {}
        if face.get("enabled", True) is not False:
            out["uv"] = [
                number(v * 16 / self.project_size[i % 2]) for i, v in enumerate(face["uv"])
            ]
        if face.get("rotation"):
            out["rotation"] = face["rotation"]
        index = face["texture"]
        if index is False or index >= len(self.textures):
            out["texture"] = "#missing"
        else:
            out["texture"] = "#" + self.textures[index]["id"]
        if face.get("cullface"):
            out["cullface"] = face["cullface"]
        if isinstance(face.get("tint"), int) and face["tint"] >= 0:
            out["tintindex"] = face["tint"]
        return out

    def compile_cube(self, cube):
        where = f"cube {cube.get('name')}"
        self.check_cube(cube, where)
        element = {}
        if cube.get("name") and cube["name"] != "cube":
            element["name"] = cube["name"]
        element["from"] = [number(c) for c in cube["from"]]
        element["to"] = [number(c) for c in cube["to"]]
        if cube.get("shade") is False:
            element["shade"] = False
        if cube.get("light_emission"):
            element["light_emission"] = cube["light_emission"]
        turned = turned_axes(cube)
        if turned or cube.get("rescale"):
            axis = turned[0] if turned else 1
            element["rotation"] = {
                "angle": number(cube["rotation"][axis]),
                "axis": "xyz"[axis],
                "origin": [number(c) for c in cube.get("origin", [0, 0, 0])],
            }
            if cube.get("rescale"):
                element["rotation"]["rescale"] = True
        element["faces"] = {
            side: self.compile_face(face)
            for side, face in cube.get("faces", {}).items()
            if face.get("texture") is not None
        }
        return element

    def compile(self):
        """The model JSON and the PNGs it uses, or None if the source breaks a rule."""
        self.check_header()
        elements = [
            element
            for element in (
                self.compile_cube(cube)
                for cube in outliner_order(self.model)
                if cube.get("type", "cube") == "cube" and cube.get("export") is not False
            )
            if element["faces"]
        ]
        shown = {
            face["texture"]
            for cube in self.model.get("elements", [])
            for face in cube.get("faces", {}).values()
            if isinstance(face.get("texture"), int) and face["texture"] < len(self.textures)
        }
        shown |= {i for i, texture in enumerate(self.textures) if texture.get("particle")}
        if len(self.errors) > self.errors_before:
            return None

        out = {"credit": f"{CREDIT} from {rel(self.path)}"}
        if self.model.get("parent"):
            out["parent"] = self.model["parent"]
        if self.model.get("ambientocclusion") is False:
            out["ambientocclusion"] = False
        render_type = (self.model.get("unhandled_root_fields") or {}).get("render_type")
        if render_type:
            out["render_type"] = render_type
        links = {}
        for index in sorted(shown):
            texture = self.textures[index]
            if texture.get("particle"):
                links["particle"] = texture_link(self.pngs[index])
            links[texture["id"]] = texture_link(self.pngs[index])
        out["textures"] = links
        if elements:
            out["elements"] = elements
        if self.model.get("front_gui_light"):
            out["gui_light"] = "front"
        if self.model.get("display"):
            out["display"] = self.model["display"]
        return out, {self.pngs[i] for i in shown}


def dump(data):
    return (json.dumps(data, indent=2) + "\n").encode("utf-8")


def is_generated(model_path):
    try:
        return json.loads(model_path.read_text(encoding="utf-8")).get("credit", "").startswith(CREDIT)
    except (OSError, ValueError, AttributeError):
        return False


def planned_files(errors):
    """Every generated path and its bytes."""
    files = {}
    for path in sorted(SOURCES.glob("*/*.bbmodel")):
        compiled = Source(path, errors).compile()
        if path.parent == TEMPLATE or compiled is None:
            continue
        model, pngs = compiled
        machine = path.stem
        if path.parent.name != machine or not RESOURCE_NAME.match(machine):
            errors.append(f"{rel(path)}: a model is named after its folder, in [a-z0-9_]")
            continue
        files[ASSETS / f"models/block/{machine}.json"] = dump(model)
        for status, lamp in STATUS_LAMPS.items():
            png = KIT / f"{lamp}.png"
            if not png.is_file():
                errors.append(f"{rel(png)} is missing")
                continue
            pngs.add(png)
            files[ASSETS / f"models/block/{machine}_{status}.json"] = dump(
                {
                    "credit": f"{CREDIT} from {rel(path)}",
                    "parent": f"{NAMESPACE}:block/{machine}",
                    "textures": {STATUS_VARIABLE: texture_link(png)},
                }
            )
        for png in pngs:
            files[texture_destination(png)] = png.read_bytes()
            mcmeta = png.with_name(png.name + ".mcmeta")
            if mcmeta.is_file():
                files[texture_destination(mcmeta)] = mcmeta.read_bytes()
    check_ownership(files, errors)
    return files


def check_ownership(files, errors):
    """Refuse to overwrite what another generator or a hand wrote, and name orphaned output."""
    models = ASSETS / "models/block"
    for path in files:
        if path.parent == models and path.is_file() and not is_generated(path):
            errors.append(f"{rel(path)} exists and was not written by this generator")
    if models.is_dir():
        for path in sorted(models.glob("*.json")):
            if path not in files and is_generated(path):
                errors.append(f"orphan: {rel(path)} has no .bbmodel any more")
    for folder in sorted({path.parent for path in files if path.parent != models}):
        if folder.is_dir():
            for path in sorted(folder.iterdir()):
                if path not in files:
                    errors.append(f"{rel(path)} is in a generated texture folder but not generated")


def check():
    errors = []
    files = planned_files(errors)
    for path, data in sorted(files.items()):
        if not path.is_file():
            errors.append(f"missing: {rel(path)}")
        elif path.read_bytes() != data:
            errors.append(f"stale: {rel(path)}")
    if errors:
        sys.exit("build-model-assets.py --check failed:\n" + "\n".join(errors))
    print(f"OK -- {len(files)} generated files current")


def build():
    errors = []
    files = planned_files(errors)
    if errors:
        sys.exit("build-model-assets.py refused:\n" + "\n".join(errors))
    for path, data in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_bytes() != data:
            path.write_bytes(data)
            print(f"wrote {rel(path)}")
    print(f"{len(files)} generated files")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    check() if args.check else build()


if __name__ == "__main__":
    main()
