#!/usr/bin/env python3
"""Emit the `factoryworks:buildings` block tag, from Factorio's placeable items (#413).

Joins `data/factorio/building.json`'s Buildings onto `data/pack/item-map.json` and writes the tag
the mod's break rule reads. An item-map target is an item, and it joins to the block of the same
id, which is looked up as a blockstate in the pack, the installed jars and the vanilla client jar,
or as a KubeJS block registration. A Building with no row, a row that is `undecided`,
`not_emitted`, `native_mechanic` or `blocked_by` a ticket, and a target that places no block of its
own id are recorded skips, printed with their reason.

Usage:

    scripts/build-building-tag.py            # writes the tag
    scripts/build-building-tag.py --check    # asserts it is already up to date; no writes
"""
import argparse
import functools
import json
import os
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "data" / "factorio" / "building.json"
ITEM_MAP = ROOT / "data" / "pack" / "item-map.json"
TAG = ROOT / "kubejs/data/factoryworks/tags/block/buildings.json"
KUBEJS = ROOT / "kubejs"
MODS = ROOT / "mods"
VANILLA = Path(os.environ.get("PF_CLIENT_JAR", os.path.expanduser(
    "~/curseforge/Install/versions/26.1.2/26.1.2.jar")))


@functools.lru_cache(maxsize=None)
def jar_blocks():
    """Every `namespace:path` a blockstate names, across the installed jars and vanilla's."""
    if not VANILLA.is_file():
        sys.exit(f"no vanilla client jar at {VANILLA} -- set PF_CLIENT_JAR")
    found = set()
    for jar in sorted(MODS.glob("*.jar")) + [VANILLA]:
        with zipfile.ZipFile(jar) as archive:
            for name in archive.namelist():
                match = re.fullmatch(r"assets/([a-z0-9_.-]+)/blockstates/([a-z0-9_/.-]+)\.json", name)
                if match:
                    found.add(f"{match.group(1)}:{match.group(2)}")
    return found


@functools.lru_cache(maxsize=None)
def kubejs_blocks():
    found = {f"{p.parent.parent.name}:{p.stem}" for p in (KUBEJS / "assets").glob("*/blockstates/*.json")}
    for script in (KUBEJS / "startup_scripts").glob("*.js"):
        for registry in script.read_text(encoding="utf-8").split("StartupEvents.registry(")[1:]:
            if registry.startswith("'block'"):
                found |= set(re.findall(r"event\.create\('([a-z0-9_]+:[a-z0-9_/]+)'\)", registry))
    return found


def is_block(target):
    return target in kubejs_blocks() or target in jar_blocks()


def tag():
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))["items"]
    items = json.loads(ITEM_MAP.read_text(encoding="utf-8"))["items"]
    blocks, skipped = set(), []
    for row in corpus:
        if not row["building"]:
            continue
        name = row["item"]
        mapped = items.get(name)
        if mapped is None:
            skipped.append(f"{name}: no item-map row")
        elif "status" in mapped:
            skipped.append(f"{name}: {mapped['status']}")
        elif "blocked_by" in mapped:
            skipped.append(f"{name}: blocked by #{mapped['blocked_by']}")
        elif "target" not in mapped:
            sys.exit(f"{name}'s row in {ITEM_MAP} has no target, status or blocked_by")
        elif mapped.get("kind") != "item":
            skipped.append(f"{name}: maps to a {mapped.get('kind')}, not an item")
        elif not is_block(mapped["target"]):
            skipped.append(f"{name}: {mapped['target']} places no block of its own id")
        else:
            blocks.add(mapped["target"])
    return sorted(blocks), skipped


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    blocks, skipped = tag()
    text = json.dumps({
        "__comment": "Generated by scripts/build-building-tag.py; do not edit. The blocks broken "
                     "at the player's full Reach rather than vanilla's 4.5 (#413).",
        "replace": False,
        "values": blocks,
    }, indent=2) + "\n"
    if args.check:
        if not TAG.is_file() or TAG.read_text(encoding="utf-8") != text:
            sys.exit(f"stale: {TAG.relative_to(ROOT)} -- run scripts/build-building-tag.py")
        print(f"OK -- {len(blocks)} Buildings")
        return
    TAG.parent.mkdir(parents=True, exist_ok=True)
    TAG.write_text(text, encoding="utf-8")
    print(f"wrote {TAG.relative_to(ROOT)}: {len(blocks)} Buildings")
    for block in blocks:
        print(f"  {block}")
    for line in skipped:
        print(f"  skip {line}")


if __name__ == "__main__":
    main()
