package com.factoryworks.core.gametest;

import java.util.List;
import java.util.function.Consumer;

import com.mojang.serialization.MapCodec;
import com.factoryworks.core.FactoryWorksCore;

import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.gametest.framework.GameTestInstance;
import net.minecraft.gametest.framework.TestData;
import net.minecraft.gametest.framework.TestEnvironmentDefinition;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Rotation;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModList;
import net.neoforged.neoforge.event.RegisterGameTestsEvent;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * The mod's GameTests, and the whole of the harness's registration side (#271).
 *
 * <p>What lands here is only what a JVM test cannot reach. {@code docs/testing/what-to-check.md}
 * asks for a GameTest when behaviour runs on world state, is not inherited from a vanilla
 * superclass, and cannot be reached without a server -- and says to split the feature first, so
 * that what is left is small. The pole's geometry and rationing, the furnace's buffer and its
 * cycle are all Minecraft-free classes with unit tests; what was left over is
 * {@link EnergyFaceTests}, and it is three tests.
 *
 * <h2>The platform</h2>
 *
 * <p>Every test here stands on {@code factoryworks:gametest/platform}, a stone floor
 * generated by {@code scripts/build-gametest-structures.py}. The blocks a test needs are placed
 * by the test, not baked into the template: two blocks written in Java are reviewable in a diff
 * and a template is not.
 */
public final class PFGameTests {

    /**
     * The one environment the pack's tests run in: no game rules changed, no clock set.
     *
     * <p>Registered rather than borrowed from {@code minecraft:default}, because the event hands
     * a mod a writable registry and no getter -- there is no way to ask for vanilla's holder here.
     */
    private static final Identifier ENVIRONMENT =
            Identifier.fromNamespaceAndPath(FactoryWorksCore.NAMESPACE, "default");

    /** The stone floor every test is placed on. */
    static final Identifier PLATFORM =
            Identifier.fromNamespaceAndPath(FactoryWorksCore.NAMESPACE, "gametest/platform");

    static final Identifier SCENE =
            Identifier.fromNamespaceAndPath(FactoryWorksCore.NAMESPACE, "gametest/scene");

    private static final DeferredRegister<MapCodec<? extends GameTestInstance>> TEST_TYPES =
            DeferredRegister.create(Registries.TEST_INSTANCE_TYPE, FactoryWorksCore.NAMESPACE);

    static {
        TEST_TYPES.register("code", () -> PFGameTestInstance.CODEC);
    }

    private PFGameTests() {
    }

    public static void register(IEventBus modBus) {
        TEST_TYPES.register(modBus);
        // The event fires only when game tests are enabled -- a production server never reaches
        // it -- so there is no guard here beyond that one.
        modBus.addListener(PFGameTests::onRegisterTests);
    }

    private static void onRegisterTests(RegisterGameTestsEvent event) {
        Holder<TestEnvironmentDefinition<?>> environment =
                event.registerEnvironment(ENVIRONMENT, new TestEnvironmentDefinition.AllOf(List.of()));
        Registrar registrar = new Registrar(event, environment);
        EnergyFaceTests.register(registrar);
        BurnerFurnaceTests.register(registrar);
        FurnaceOverloadTests.register(registrar);
        HandSetTests.register(registrar);
        AssemblingFamilyTests.register(registrar);
        PlacementPlanTests.register(registrar);
        BoilerTests.register(registrar);
        RigBreakTests.register(registrar);
        ElectricRigTests.register(registrar);
        WorldgenFixtureTests.register(registrar);
        OutfieldDiscTests.register(registrar);
        OilFieldTests.register(registrar);
        ReachTests.register(registrar);
        SpawningRuleTests.register(registrar);
        ChestTests.register(registrar);
        PackChestTests.register(registrar);
        WreckTests.register(registrar);
        // Oritech is optional, and the class names its types, so it is not even loaded without it.
        if (ModList.get().isLoaded("oritech")) {
            SteamEngineNetworkTests.register(registrar);
            AccumulatorTests.register(registrar);
            SolarPanelTests.register(registrar);
            AssemblingMachineTests.register(registrar);
            AssemblingFluidTests.register(registrar);
            ChemicalPlantTests.register(registrar);
            OilRefineryTests.register(registrar);
            PlacementPlanTests.AssemblingReplaces.register(registrar);
            FootprintBreakTests.register(registrar);
            ReachTests.Screens.register(registrar);
            RadarTests.register(registrar);
            PumpjackTests.register(registrar);
            PipeDismantleTests.register(registrar);
            PipeStretchTests.register(registrar);
        }
        if (ModList.get().isLoaded("beltworks")) {
            BeltworksPackTests.register(registrar);
        }
        if (ModList.get().isLoaded("oritech") && ModList.get().isLoaded("beltworks")) {
            ShowcaseSceneTests.register(registrar);
        }
    }

    /** What a test file is handed: a name, a tick budget and a body. */
    record Registrar(RegisterGameTestsEvent event, Holder<TestEnvironmentDefinition<?>> environment) {

        void test(String name, int maxTicks, Consumer<GameTestHelper> body) {
            Identifier id = Identifier.fromNamespaceAndPath(FactoryWorksCore.NAMESPACE, name);
            PFGameTestInstance.define(id, body);
            event.registerTest(id, new PFGameTestInstance(id, new TestData<>(
                    environment, PLATFORM, maxTicks, 0, true, Rotation.NONE)));
        }

        // Its own namespace keeps a scene out of the check run's `factoryworks:*` (#538).
        void showcase(String name, int maxTicks, Consumer<GameTestHelper> body) {
            Identifier id = Identifier.fromNamespaceAndPath("factoryworks_showcase", name);
            PFGameTestInstance.define(id, body);
            event.registerTest(id, new PFGameTestInstance(id, new TestData<>(
                    environment, SCENE, maxTicks, 0, true, Rotation.NONE)));
        }
    }
}
